version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - nginx

  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    volumes:
      - disquaire-pg-data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

volumes:
  disquaire-pg-data:
