version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - disquaire-static-data:/app/disquaire_project/staticfiles

  postgres:
    image: library/postgres:10.15
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - disquaire-pg-data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - disquaire-static-data:/home/disquaire/disquaire_project/staticfiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

volumes:
  disquaire-pg-data:
  disquaire-static-data:
