version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    volumes:
      - disquaire-pg-data:/var/lib/postgresql/data/

volumes:
  disquaire-pg-data:
